<?php
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Home;
use App\Http\Controllers\Group;
use App\Http\Controllers\Kala;
use App\Http\Controllers\Basket;
use App\Http\Controllers\Order;
use App\Http\Controllers\Customer;
use App\Http\Controllers\Factor;
use App\Http\Controllers\Lottery;
use App\Http\Controllers\Message;
use App\Http\Controllers\TakhfifCode;
use App\Http\Controllers\Game;
use App\Http\Controllers\Cheque;
use App\Http\Controllers\ChatMessage;
use App\Http\Controllers\AuthController;

// \Artisan::call("route:clear");
Route::middleware('auth:sanctum')->get('/user', function (Request $request) { return $request->user(); });
Route::get('/getMainGroups',[Group::class,'getMainGroups']);
Route::get('/getSubGroupList',[Group::class,'getSubGroupList']);
Route::get('/getMainGroupKala',[Group::class,'getMainGroupKala']);
Route::get('/getUnitsForUpdate',[Kala::class,'getUnitsForUpdate']);
Route::get('/appendSubGroupKala',[Kala::class,'appendSubGroupKalaApi']);
Route::get('/buySomething',[Kala::class,'buySomethingApi']);
Route::get('/updateOrderBYS',[Basket::class,'updateOrderBYS']);
Route::get('/deleteOrderBYS',[Basket::class,'deleteOrderBYS']);
Route::get('/setFavorite',[Kala::class,'setFavoriteApi']);
Route::get('/favoritKalaApi',[Kala::class,'favoritKalaApi']);
Route::get('/shippingData',[Basket::class,'shippingData']);
Route::get('/addFactorApi',[Order::class,'addFactorApi']);
Route::get('/successFactorInfo',[Basket::class,'successFactorInfo']);
Route::get('/profile', [Customer::class,'indexApi']);
Route::get('/listFactors', [Factor::class,'indexApi']);
Route::get('/cartsList',[Basket::class,'cartsListApi']);
Route::get('/factorView',[Factor::class,'factorViewApi']);
Route::get('/getHeaderInfo',[Home::class,'getHeaderInfoApi']);
Route::get('/wallet',[Customer::class,'walletApi']);
Route::get('/bagCash',[Lottery::class,'indexApi']);
Route::get('/descKala',[Kala::class,'descKalaApi']);
Route::get('/addRequestedProduct',[Kala::class,'addRequestedProduct']);
Route::get('/cancelRequestedProduct',[Kala::class,'cancelRequestedProduct']);
Route::get('/messageList',[Message::class,'indexApi']);
Route::get('/doAddMessage',[Message::class,'doAddMessageApi']);
Route::get('/updateChangedPrice',[Basket::class,'updateChangedPriceApi']);
Route::get('/searchKala',[Kala::class,'searchKalaApi']);
Route::get('/listOrders', [Order::class, 'listOrdersApi']);
Route::get("/addMoneyToCase",[Customer::class,"addMoneyToCaseApi"]);
Route::get("/getSlidersApi",[Home::class,"getSlidersApi"]);
Route::get('/addIntroducerCode',[Customer::class,'addIntroducerCodeApi']);
Route::get('/logOutConfirm',[Customer::class,'logOutConfirmApi']);
Route::get("/loginApi",[AuthController::class,"login"]);
Route::get("/checkLogin",[AuthController::class,"checkLoginApi"]);
Route::get("/checkTakhfifCodeReliablity",[TakhfifCode::class,"checkTakhfifCodeReliablity"]);
Route::get("/getGamerList",[Game::class,"getGamerList"]);
Route::get("/getTakhfifAndPrize",[TakhfifCode::class,"getTakhfifAndPrize"]);
Route::get("/getLotteryInfoApi",[Lottery::class,"getLotteryInfoApi"]);
Route::get("/setWeeklyPresentApi",[Customer::class,"setWeeklyPresentApi"]);
Route::get("/getInviteCodeApi",[Customer::class,"getInviteCodeApi"]);
Route::get("/setCustomerLotteryHistory",[Lottery::class,"setCustomerLotteryHistory"]);
Route::get("/getPaymentFormApi",[Order::class,"getPaymentFormApi"]);
Route::post("/addRequestCheck",[Cheque::class,"addRequestCheck"]);
Route::get("/getChequeReqState",[Cheque::class,"getChequeReqState"]);
Route::get('/successPayApi',[Order::class,'finalizePayAndOrderApi']);
Route::get("/publicSearchKalaApi",[Kala::class,"publicSearch"]);
Route::get("/getFactorPaymentFormApi",[Order::class,"getFactorPaymentFormApi"]);
Route::get("/finalizeFactorPayApi",[Order::class,"finalizeFactorPayApi"]);
Route::get("/getChatMessages",[ChatMessage::class,"getChatMessages"]);
Route::get("/addMessage",[ChatMessage::class,"addMessage"]);
Route::get("/replayMessage",[ChatMessage::class,"replayMessage"]);
Route::get("/getHomeParts",[Home::class,"getHomeParts"]);
Route::get("/addToBasketFromHomePageApi",[Basket::class,"addToBasketFromHomePageApi"]);
Route::get("/updateBasketItemFromHomePage",[Basket::class,"updateBasketItemFromHomePage"]);
Route::get("/irregularLoginApi",[AuthController::class,"irregularLoginApi"]);
Route::get("/getAllMainGroupBranches",[Group::class,"getAllMainGroupBranches"]);
Route::get("/getAttractiveVisits",[App::class,"getAttractiveVisits"]);
Route::get("/setAttractiveVisits",[App::class,"setAttractiveVisits"]);